# Generated by Django 3.1 on 2023-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='status',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
